baseURL = "https://hou.l0v0.com"
title = "Houdini Wiki"
# theme = ["zdoc","zzo"]
theme = ["zdoc"]
# theme = ["zzo"]
enableInlineShortcodes = true

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

buildFuture = true
summaryLength = 70

copyright = "&copy;{year}, All Rights Reserved"
disableAliases = true
enableEmoji = true
paginate = 13
rssLimit = 100
timeout = 10000

googleAnalytics = ""

enableEditBtn = true

publishDir = "docs"
# disableKinds = ["taxonomyTerm"]
minify = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = true
unsafe = true
xHTML = true
[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
# section = ["HTML", "RSS", "SearchIndex"]
# taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
# taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
[outputFormats.SearchIndex]
baseName = "index"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[taxonomies]
category = "categories"
level = "level"
nodes = "nodes"
pipeline = "pipeline"
producer = "producer"
tag = "tags"
version = "version"

[related]

includeNewer = true
threshold = 80
toLower = false

# [[related.indices]]
# name = "date"
# pattern = "2006"
# weight = 10
[[related.indices]]
name = "pipeline"
weight = 30
[[related.indices]]
name = "nodes"
weight = 40
[[related.indices]]
name = "level"
weight = 5
[[related.indices]]
name = "version"
weight = 5
