
[[main]]
  identifier = "learning"
  name = "学习路线"
  url = "1_learning"
  weight = 1

  [[main]]
    parent = "learning"
    identifier = "beginner"
    name = "入门"
    url = "2_beginner"
    weight = 2

  [[main]]
    parent = "learning"
    identifier = "vex"
    name = "Vex"
    url = "3_vex"
    weight = 3
    
  [[main]]
    parent = "learning"
    identifier = "python"
    name = "Python"
    url = "4_python"
    weight = 4

  [[main]]
    parent = "learning"
    identifier = "math"
    name = "数学"
    url = "5_math"
    weight = 5

  [[main]]
    parent = "learning"
    identifier = "procedural"
    name = "程序化生成"
    url = "6_procedural"
    weight = 6

  [[main]]
    parent = "learning"
    identifier = "FX"
    name = "影视特效"
    url = "15_fx"
    weight = 15

  [[main]]
    parent = "learning"
    identifier = "rendering"
    name = "渲染"
    url = "16_rendering"
    weight = 16

  [[main]]
    parent = "learning"
    identifier = "msic"
    name = "杂项"
    url = "19_msic"
    weight = 19

[[main]]
  identifier = "nodes"
  name = "节点"
  url = "20_nodes"
  weight = 10

  [[main]]
    parent = "nodes"
    identifier = "chop"
    name = "CHOP"
    url = "20_nodes/chop"
    weight = 1

  [[main]]
    parent = "nodes"
    identifier = "COP2"
    name = "COP2"
    url = "20_nodes/cop2"
    weight = 2

  [[main]]
    parent = "nodes"
    identifier = "DOP"
    name = "DOP"
    url = "20_nodes/dop"
    weight = 3

  [[main]]
    parent = "nodes"
    identifier = "LOP"
    name = "LOP"
    url = "20_nodes/lop"
    weight = 4

  [[main]]
    parent = "nodes"
    identifier = "OBJ"
    name = "OBJ"
    url = "20_nodes/obj"
    weight = 5

  [[main]]
    parent = "nodes"
    identifier = "ROP"
    name = "ROP"
    url = "20_nodes/rop"
    weight = 6

  [[main]]
    parent = "nodes"
    identifier = "SOP"
    name = "SOP"
    url = "20_nodes/sop"
    weight = 7

  [[main]]
    parent = "nodes"
    identifier = "TOP"
    name = "TOP"
    url = "20_nodes/top"
    weight = 8

  [[main]]
    parent = "nodes"
    identifier = "VOP"
    name = "VOP"
    url = "20_nodes/vop"
    weight = 9

[[main]]
  identifier = "categories"
  name = "分类"
  url = "archive/"
  weight = 15

  [[main]]
    parent = "categories"
    identifier = "cat_producer"
    name = "出品方"
    url = "producer/"
    weight = 1

  [[main]]
    parent = "categories"
    identifier = "cat_level"
    name = "难度"
    url = "level/"
    weight = 2

  [[main]]
    parent = "categories"
    identifier = "cat_pipeline"
    name = "流程"
    url = "pipeline/"
    weight = 3

  [[main]]
    parent = "categories"
    identifier = "cat_nodes"
    name = "Houdini 模块"
    url = "nodes/"
    weight = 4

  [[main]]
    parent = "categories"
    identifier = "cat_versions"
    name = "Houdini 版本"
    url = "version/"
    weight = 5

[[main]]
  identifier = "blog"
  name = "博客"
  url = "blog"
  weight = 20

  [[main]]
    parent = "blog"
    identifier = "translate"
    name = "翻译转载"
    url = "translate"
    weight = 5

[[main]]
  identifier = "updates"
  name = "关于"
  url = "updates/about"
  weight = 25
  
