
[[main]]
  identifier = "learning"
  name = "学习路线"
  url = "learning"
  weight = 1

  [[main]]
    parent = "learning"
    identifier = "beginner"
    name = "入门"
    url = "beginner"
    weight = 2

  [[main]]
    parent = "learning"
    identifier = "vex"
    name = "Vex"
    url = "vex"
    weight = 3
    
  [[main]]
    parent = "learning"
    identifier = "python"
    name = "Python"
    url = "python"
    weight = 4

  [[main]]
    parent = "learning"
    identifier = "math"
    name = "数学"
    url = "math"
    weight = 5

  [[main]]
    parent = "learning"
    identifier = "game"
    name = "游戏引擎"
    url = "game"
    weight = 6

  [[main]]
    parent = "learning"
    identifier = "FX"
    name = "影视特效"
    url = "fx"
    weight = 15

  [[main]]
    parent = "learning"
    identifier = "rendering"
    name = "渲染"
    url = "rendering"
    weight = 16

  [[main]]
    parent = "learning"
    identifier = "msic"
    name = "杂项"
    url = "msic"
    weight = 19

[[main]]
  identifier = "nodes"
  name = "节点"
  url = "nodes"
  weight = 10

  [[main]]
    parent = "nodes"
    identifier = "chop"
    name = "CHOP"
    url = "nodes/chop"
    weight = 1

  [[main]]
    parent = "nodes"
    identifier = "COP2"
    name = "COP2"
    url = "nodes/cop2"
    weight = 2

  [[main]]
    parent = "nodes"
    identifier = "DOP"
    name = "DOP"
    url = "nodes/dop"
    weight = 3

  [[main]]
    parent = "nodes"
    identifier = "LOP"
    name = "LOP"
    url = "nodes/lop"
    weight = 4

  [[main]]
    parent = "nodes"
    identifier = "OBJ"
    name = "OBJ"
    url = "nodes/obj"
    weight = 5

  [[main]]
    parent = "nodes"
    identifier = "ROP"
    name = "ROP"
    url = "nodes/rop"
    weight = 6

  [[main]]
    parent = "nodes"
    identifier = "SOP"
    name = "SOP"
    url = "nodes/sop"
    weight = 7

  [[main]]
    parent = "nodes"
    identifier = "TOP"
    name = "TOP"
    url = "nodes/top"
    weight = 8

  [[main]]
    parent = "nodes"
    identifier = "VOP"
    name = "VOP"
    url = "nodes/vop"
    weight = 9

[[main]]
  identifier = "categories"
  name = "分类"
  url = "archive/"
  weight = 15

  [[main]]
    parent = "categories"
    identifier = "cat_producer"
    name = "出品方"
    url = "producer/"
    weight = 1

  [[main]]
    parent = "categories"
    identifier = "cat_level"
    name = "难度"
    url = "level/"
    weight = 2

  [[main]]
    parent = "categories"
    identifier = "cat_pipeline"
    name = "流程"
    url = "pipeline/"
    weight = 3

  [[main]]
    parent = "categories"
    identifier = "cat_nodes"
    name = "Houdini 模块"
    url = "nodes/"
    weight = 4

  [[main]]
    parent = "categories"
    identifier = "cat_versions"
    name = "Houdini 版本"
    url = "version/"
    weight = 5

[[main]]
  identifier = "blog"
  name = "博客"
  url = "blog"
  weight = 20

  [[main]]
    parent = "blog"
    identifier = "translate"
    name = "翻译转载"
    url = "translate"
    weight = 5

[[main]]
  identifier = "updates"
  name = "关于"
  url = "updates/about"
  weight = 25
  
  [[main]]
    parent = "updates"
    identifier = "log"
    name = "更新日志"
    url = "updates/log"
    weight = 1
  
  [[main]]
    parent = "updates"
    identifier = "todo"
    name = "待办列表"
    url = "updates/todo"
    weight = 2