

[[main]]
  identifier = "nodes"
  name = "节点"
  url = "1_nodes"
  weight = 1

[[main]]
  identifier = "examples"
  name = "案例"
  url = "2_examples"
  weight = 2
  
[[main]]
  identifier = "vex"
  name = "Vex"
  url = "3_vex"
  weight = 3
  
[[main]]
  identifier = "python"
  name = "Python"
  url = "4_python"
  weight = 4
  
[[main]]
  identifier = "game"
  name = "游戏"
  url = "5_game"
  weight = 5

[[main]]
  identifier = "math"
  name = "数学"
  url = "6_math"
  weight = 6

[[main]]
  identifier = "blog"
  name = "博客"
  url = "blog"
  weight = 7


[[main]]
  identifier = "updates"
  name = "更新记录"
  url = "updates"
  weight = 8
  