name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: collect links.json
        run: python ./content/collection_link_data.py

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        
      - name: Install SSH Key
        # You may pin to the exact commit or the version.
        # uses: shimataro/ssh-key-action@6f350ca8484d8d55c2e361e74d17e638dabe713a
        uses: shimataro/ssh-key-action@v2.1.0
        with:
          # SSH private key
          key: ${{ secrets.SERVER_SSH }}
          known_hosts: ${{ secrets.SERVER_SSH_PUB }}
          name: blog
          config: |                                         # will be appended!
            Host l0v0.com
              HostName ${{ secrets.SERVER_IP }}
              User git
              IdentityFile ~/.ssh/blog
      # - name: push to Server
          
      - name: push repo
        run: | 
          git remote add server git@l0v0.com:/home/git/repos/HoudiniWiki.git 
          git checkout gh-pages
          git pull origin gh-pages
          git push server gh-pages